### ISSUE TITLE
[Bug]: accessing run summary raises exception (starting in 0.22.1)

### ISSUE THREAD

**Issue by mkoehrsen** [wandb/wandb#10711]
### Describe the bug

If I retrieve runs using Api.runs() and then try to access a run summary, I get an exception like:

```
  File "/home/user/workspace/osmo/test_wandb.py", line 7, in <module>
    print(runs[0].summary)
  File "/home/user/.conda/envs/osmo/lib/python3.11/site-packages/wandb/old/summary.py", line 152, in __repr__
    v = self._json_dict[k]
        ~~~~~~~~~~~~~~~^^^
TypeError: string indices must be integers, not 'str'
```

The bug seems to have been introduced in release 0.22.1 and is also present in 0.22.2. Downgrading to 0.22.0 fixes it. See attachment for a minimal test case.

[test_wandb.py](https://github.com/user-attachments/files/22953319/test_wandb.py)

**Comment by ffelten** [comment]
+1, we've got this for `config`, too.

**Comment by Anshuman-WandB** [comment]
Hi @mkoehrsen and @ffelten ,

Thanks for flagging this, this was a known regression introduced in v0.22.1. I'm happy to report that this was fixed in a pull request last week: [#10682](https://github.com/wandb/wandb/pull/10682).

The fix will be included in our next SDK release. I'll go ahead and close this issue now, but please feel free to reopen it if the problem persists after you upgrade.

Thanks again for your contribution!

**Comment by samuelstevens** [comment]
This bug still exists in v0.22.2. 

Making a file `test_wandb.py` with the following contents:

```py
# /// script
# requires-python = ">=3.12"
# dependencies = [
#     "wandb==0.22.2",
# ]
# ///
import wandb

for run in wandb.Api().runs(path="samuelstevens/saev"):
    print(run.id)
    print(run.summary.keys())
    break
```

Then `uv run test_wandb.py` will throw the same error.

**Comment by Anshuman-WandB** [comment]
Hey @samuelstevens,

Thanks for following up on this, and apologies for the confusion. You are correct, that bug was still present in v0.22.2. As @mkoehrsen mentioned above.

> The bug seems to have been introduced in release 0.22.1 and is also present in 0.22.2

The fix (PR #10682) was merged and included in the v0.22.3 release. If you upgrade to wandb to v0.22.3, this issue should be resolved.

You can see the [release notes for v0.22.3 here](https://github.com/wandb/wandb/releases/tag/v0.22.3), which includes that fix.

Please let us know if you run into any issues after upgrading!
