### ISSUE TITLE
[CLI] With WANDB_MODE=offline python client still try to sync results

### ISSUE THREAD

**Issue by cssb** [wandb/wandb#2701]
**Description**
I use W&B on a server without an Internet connection.
For working with W&B, I set WANDB_MODE=offline then sync my runs from another machine with an Internet connection.
All work fine until I update to wandb version 0.12.2.
With version 0.12.2 when the program ends, I get the message:
"... wandb: Network error (ConnectTimeout), entering retry loop."
and the program cannot terminate.

The code to reproduce,  run on a machine without internet connection:
```python
# test_wandb_offline.py
import os
os.environ["WANDB_MODE"]="offline"

import numpy as np
import pandas as pd
import wandb


if __name__ == "__main__":
    print(wandb.__version__)
    wandb.init(project="my_wandb_test_project")
    wandb.config["run_1"] = 1
    wandb.log({"val_1":1})
    wandb.log({"val_1":2})
    wandb.log({"val_1":3})
    wandb.summary.update({"val_2":123})
    print("Done!")
```

With wandb version 0.12.2 the program cannot terminate and output looks like:
```
0.12.2
wandb: W&B syncing is set to `offline` in this directory.  Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.
~/anaconda/lib/python3.8/site-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.6) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Done!

wandb: Waiting for W&B process to finish, PID 24846
wandb: Program ended successfully.
wandb: Network error (ConnectTimeout), entering retry loop.
```

With wandb version 0.12.1 and early, the program terminates normally.

**Environment**
- OS: CentOS Linux release 7.9.2009 (Core)
- Environment: n/a
- Python Version: 3.7.0

**Comment by donlaiq** [comment]
Hello cssb,

Maybe, I am not a good reference at all (I've installed wandb just a few minutes ago), but I've run exactly the same code you are mentioning in the post, and it runs flawlessly.
Just for your reference, I've created a brand new virtual environment with Python 3.7.3, where I'm installing just numpy, pandas and wandb (just the required libraries), and my OS is Debian 10.

`wandb: Waiting for W&B process to finish, PID ...
wandb: Program ended successfully.
wandb: Find user logs for this run at...`

**Comment by cssb** [comment]
Hello donlaiq, are you running this code on the offline machine (without connection to the Internet)?

**Comment by donlaiq** [comment]
Oh, boy! No I wasn't. In that case, you are right, I'm running in the same issue.

**Comment by tomgreen66** [comment]
Hitting same issue whilst supporting a HPC cluster where compute nodes do not have access to Internet.  With 0.21 the user reported success so definitely a regression in latest version.  Tried chasing where the regression slipped in - but hopefully someone more familiar with the code will chase it.

**Comment by tomgreen66** [comment]
Having just done a `git bisect` looks like #2513 is a possible first culprit. 

```
c9cb5c8305b9d73e0f4b8b294f9a7de89b54d807 is the first bad commit
commit c9cb5c8305b9d73e0f4b8b294f9a7de89b54d807
Author: Katia Patkin <87335417+kptkin@users.noreply.github.com>
Date:   Wed Sep 1 18:31:01 2021 -0700

    [WB-6267] Print a warning when the local instance is stale (#2513)
    
    * print warning for local instance with introspection and caching

:040000 040000 ef7e412151a6e3c5d235a8ae09463a5e7c356f52 e40b53dfef3cccbe3b567f6062356e857d57b7f0 M      tests
:100644 100644 5df81a2aa7bba23fee2341218f46ac5f410adb0e 4b0dc5a92c868a8f49adfef0d7cbe62f7af85be5 M      tox.ini
:040000 040000 6f990708746058e51043d4b986d1c3508463adb4 299e1c04e60fda7a3b2be55b876d9a08a61e33c6 M      wandb
```

**Comment by Tim-Chard** [comment]
I have also hit this issue on a HPC cluster with 0.12.2 and 0.12.3 but 0.12.1 works fine.

**Comment by vanpelt** [comment]
Thanks for the report, we're tracking this and will get a fix in the next release.  Until then please use 0.12.1 on nodes without internet and `WANDB_MODE=offline`.

**Comment by raubitsj** [comment]
Thank you for the report and tracking down the commit!
We have released a fix in 0.12.4
https://github.com/wandb/client/releases/tag/v0.12.4

**Comment by nicolas-dufour** [comment]
Hi, i'm still having the same problem on 0.12.14 on an HPC that doesn't have internet access. More specifically, I'm running PyTorch lightning 1.6.0 and have no problem for the first training logging, but the error appears when finishing the first validation epoch. Also running the same code on a computer having internet access but with offline mode, the problem doesn't appear. Didn't have the problem previously on 0.12.4.

**Comment by nicolas-dufour** [comment]
Hi @raubitsj, could this be reponend, the error is still occurring in recent versions. It's quite annoying and is limiting the use of wandb in academic clusters. Thanks!

**Comment by kptkin** [comment]
Hi @nicolas-dufour sorry to see that you are still experiencing issues.
Could you please help us debug this issue, by providing:
- a reproduction for your case, based on the other reporting, the original issues, should be fixed (as we don't check the local version) in offline mode anymore. So it could be some other api call we are trying to make in offline mode. 
- Also do you know what is the last working version wandb for you?

Thanks!

**Comment by cemde** [comment]
still happens in `0.14.2`. I do

```
os.environ["WANDB_MODE"] = "offline"
run = wandb.init(mode="offline")
...
run.finish()
```

and that still tries to connect to the server

**Comment by kptkin** [comment]
@cemde Thanks for reporting the issue. I tried version `0.14.2` and it works as expected and i don't see any attempts to connect to the server. Could you please provide a reproduction of the issue you are seeing?

**Comment by ddonatien** [comment]
Running wandb 0.15.7, with 

```python
os.environ["WANDB_MODE"] = "offline"
wandb.init(mode="offline")``` 
I get the following error:

```wandb: ERROR Connection to wandb service failed: [Errno -2] Name or service not known
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/wandb_manager.py", line 115, in _service_connect
    svc_iface._svc_connect(port=port)
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/service/service_sock.py", line 30, in _svc_connect
    self._sock_client.connect(port=port)
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/lib/sock_client.py", line 102, in connect
    s.connect(("localhost", port))
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/neuphysics/run.py", line 879, in <module>
    wandb.init(project="neuphysics",
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/wandb_init.py", line 1166, in init
    raise e
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/wandb_init.py", line 1143, in init
    wi.setup(kwargs)
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/wandb_init.py", line 172, in setup
    self._wl = wandb_setup.setup(settings=setup_settings)
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/wandb_setup.py", line 327, in setup
    ret = _setup(settings=settings)
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/wandb_setup.py", line 320, in _setup
    wl = _WandbSetup(settings=settings)
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/wandb_setup.py", line 303, in __init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings, pid=pid)
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/wandb_setup.py", line 114, in __init__
    self._setup()
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/wandb_setup.py", line 250, in _setup
    self._setup_manager()
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/wandb_setup.py", line 277, in _setup_manager
    self._manager = wandb_manager._Manager(settings=self._settings)
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/wandb_manager.py", line 162, in __init__
    wandb._sentry.reraise(e)
  File "/usr/local/lib/python3.8/dist-packages/wandb/analytics/sentry.py", line 154, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/wandb_manager.py", line 160, in __init__
    self._service_connect()
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/wandb_manager.py", line 126, in _service_connect
    raise ManagerConnectionError(f"Connection to wandb service failed: {e}")
wandb.sdk.wandb_manager.ManagerConnectionError: Connection to wandb service failed: [Errno -2] Name or service not known
wandb: While tearing down the service manager. The following error has occurred: 'SockClient' object has no attribute '_sock'```

How can I disable all attempt at connecting anywhere ?

**Comment by greatwallet** [comment]
still happens in 0.15.12

**Comment by zhangchuheng123** [comment]
wandb.init(mode='offline') still try to connect to the server resulting in a ConnectionRefusedError: [Errno 111] Connection refused error in 0.15.10.

**Comment by raymondchua** [comment]
I am using  0.16.6 and I do not encounter the error after setting it to offline mode:

**Comment by raymondchua** [comment]
> Does anyone have a solution? I am using wandb 0.16.5 and still have this issue when I run a sweep.

In the end, I revert back to version 0.13.5 where everything seems to be working fine.

**Comment by Anri-Lombard** [comment]
Still happens to this day with version  0.17.4

**Comment by Anri-Lombard** [comment]
I can back @raymondchua; 0.13.5 seems to be perfectly fine.

**Comment by sephmard** [comment]
@juliafalcao this should be resolved when using our new Go backend service: https://wandb.me/wandb-core. It is quite simple to enable. We also introduced a new sync cli command wandb beta sync that only works with the new backend, not advertising it yet. Mind confirming that it fixes your issue?

**Comment by juliafalcao** [comment]
> @juliafalcao this should be resolved when using our new Go backend service: https://wandb.me/wandb-core. It is quite simple to enable. We also introduced a new sync cli command wandb beta sync that only works with the new backend, not advertising it yet. Mind confirming that it fixes your issue?

I don't think it fixed the issue, I have `wandb.require('core')` before my `wandb.init` and `WANDB_MODE=offline` and it still tries to connect:

```
wandb: Tracking run with wandb version 0.17.7
wandb: W&B syncing is set to `offline` in this directory.  
wandb: Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.
(...)
wandb: Run summary:
(...)

wandb: You can sync this run to the cloud by running:
wandb: wandb sync /gpfs/projects/bsc88/text/bias/decomposing/wandb/offline-run-20240905_124848-9cwv5hnd
wandb: Find logs at: ./wandb/offline-run-20240905_124848-9cwv5hnd/logs
2024-09-05 12:57:02,137 [connectionpool.py] WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc20c63dc10>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /api/4504800232407040/envelope/
2024-09-05 12:57:02,141 [connectionpool.py] WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc20c63e300>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /api/4504800232407040/envelope/
2024-09-05 12:57:02,144 [connectionpool.py] WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc1ed87f920>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /api/4504800232407040/envelope/
2024-09-05 12:57:02,152 [connectionpool.py] WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc20c61fd70>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /api/4504800232407040/envelope/
2024-09-05 12:57:02,156 [connectionpool.py] WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc20c6923c0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /api/4504800232407040/envelope/
2024-09-05 12:57:02,159 [connectionpool.py] WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc20c63d4c0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /api/4504800232407040/envelope/
```

**Comment by nicolas-dufour** [comment]
Hi @sephmard, I'm still having this error on 0.19.0

**Comment by jacobromero** [comment]
Hi @nicolas-dufour I am having trouble reproducing this error.
Could you share some details about your environment.

- What python version are you using
- A script similar to the one you are running (if different from the one in the details of this issue)
- the console output from your script

**Comment by thomaslonneville** [comment]
I am also having this issue on wandb 0.18.7. I notice that there is no problem for a 'normal _wandb.log_ of data'. However if I want to log a wandb table, the Network error occurs.

**Comment by liboqiao1234** [comment]
I also have this issue. My version: wandb 0.19.6.
I am new to this tool (wandb) and just know that I set wandb.init(mode="offline") and still encounter errors happened in `SocketClient` during my train.

Because my network is not always stable so I try to use `offline` mode to run and sync it afterwards.

**Comment by jacobromero** [comment]
Thank you @thomaslonneville and @liboqiao1234 for commenting this.

I have tried to reproduce this with the info you have provided but I am not getting any network errors while doing `wandb sync`.
Does this happen immediately after running `wandb sync`, or after some time?

Also would you be able to provide your logs for the command? Typically located at `./wandb/debug-cli.{user-name}.log`

**Comment by thomaslonneville** [comment]
Dear @jacobromero I get this error during training in offline mode. So not afterwards when conducting ```wandb sync```.

**Comment by jacobromero** [comment]
Hi @thomaslonneville looks like there was an issue that was fixed in [v0.19.5](https://github.com/wandb/wandb/releases/tag/v0.19.5) which for some datatypes that were backed by W&B artifacts, were still attempting to make a network call.

Could you try updating to v0.19.5 or later and that should resolve your issue!

**Comment by dmitryduev** [comment]
Closing as likely fixed.
