### ISSUE TITLE
[CLI]: Hyperparameter Sweeps doesn't Work for Nested Configs if wandb is Run Locally

### ISSUE THREAD

**Issue by rachmadionl** [wandb/wandb#3702]
### Describe the bug

When I tried nested configurations for hyperparmater sweeps locally, it returns `Invalid sweep config: invalid hyperparameter` error.
EDIT: I could run sweep with nested configuration if wandb is run from **cloud**. Apparently this bug appears only when I run wandb **locally**.

``` 
description: sweep using nested params

# Training script to run
program: train-nested-cli.py

# Method can be bayes, random, grid
method: grid

# Metric to optimize
metric:
  name: loss
  goal: minimize

# Parameter space to search
parameters:
  batch_size:
    values: [32, 64]
  optimizer:
    parameters:
      # lr parameter is nested behind "optimizer"
      lr:
        values: [0.001, 0.0001]
      nadam:
        parameters:
        # beta parameter is nested behind "opimizer.nadam"
          beta:
            values: [0.9, 0.95]
```

```shell

Invalid sweep config: invalid hyperparameter configuration: optimizer
```

### Additional Files

The config files above was taken from the example here: https://github.com/wandb/sweeps/blob/master/examples/nested-params/using-cli/sweep-nested.yaml

### Environment

WandB version: 0.12.16

OS: Ubuntu 18.04

Python version: 3.8.13

Versions of relevant libraries:

**Comment by armanhar** [comment]
Hey @rachmadionl, we started supporting nested configs recently, so it may be the case that the local version is not yet updated. I'll double-check and let you know.

**Comment by armanhar** [comment]
Hey @rachmadionl, I can confirm that the local versions don't yet support the feature. You can expect a new version of W&B Local next month which should include the update regarding nested configs.

**Comment by rachmadionl** [comment]
@armanhar understood, I'll be waiting for the next version to release then! I'll close the issue for now.

**Comment by rachmadionl** [comment]
hi there @armanhar, I think this issue is solved as I can use Nested Configs for the local wandb (I actually tried a few months ago but forgot to give a comment on this one, sorry). Maybe we can close this issue?

**Comment by ahalev** [comment]
I am still having this issue with `wandb=0.15.91`:

```python
400 response executing GraphQL.
{"errors":[{"message":"Invalid sweep config: invalid hyperparameter configuration: preprocess","path":["upsertSweep"]}],"data":{"upsertSweep":null}}
wandb: ERROR Error while calling W&B API: Invalid sweep config: invalid hyperparameter configuration: preprocess (<Response [400]>)
```

I am getting this by calling

```python
import wandb

sweep_config = {'early_terminate': {'type': 'hyperband', 'min_iter': 8, 'eta': 2, 's': 4},
 'method': 'grid',
 'metric': {'goal': 'maximize',
            'name': 'Evaluate/balanced_accuracy',
            'target': 0.95},
 'parameters': {'preprocess': {'laplacian_filter': {'kernels': {'values': [[None,
                                                                            [41,
                                                                             41]],
                                                                           [None,
                                                                            None]]}}},
                'project': {'value': 'retinal_genotype'},
                'train_config': {'optimizer': {'lr': {'values': [1e-06,
                                                                 0.0001,
                                                                 0.01]},
                                               'sgd': {'momentum': {'values': [0.0,
                                                                               0.5,
                                                                               0.9,
                                                                               0.99]}},
                                               'weight_decay': {'values': [1e-06,
                                                                           0.0001,
                                                                           0.01]}},
                                 'scheduler': {'warmup': {'values': [0,
                                                                     5,
                                                                     20]}}}},
 'program': '../trainer.py',
 'project': 'retinal_genotype'}

wandb.sweep(sweep_config)

```

**Comment by ReedMerrill** [comment]
Like @ahalev, I am still experiencing this issue. I am on wandb 0.16.1. What is the alternative to a nested config?
