### ISSUE TITLE
[Q] wandb stream ID error

### ISSUE THREAD

**Issue by dyhan316** [wandb/wandb#4872]
I tried running using wandb with optuna. Most of the times it works but some times the following error occurs and this code runs but the results are not sent to the wandb website (only the system information like CPU usage and so on gets sent)

```
Exception in thread SockSrvRdThr:...
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/connectome/dyhan316/.conda/envs/VAE_3DCNN_older_MONAI/lib/python3.8/site-packages/wandb/sdk/service/server_sock.py", line 112, in run
    shandler(sreq)
  File "/home/connectome/dyhan316/.conda/envs/VAE_3DCNN_older_MONAI/lib/python3.8/site-packages/wandb/sdk/service/server_sock.py", line 174, in server_record_publish
    iface = self._mux.get_stream(stream_id).interface
  File "/home/connectome/dyhan316/.conda/envs/VAE_3DCNN_older_MONAI/lib/python3.8/site-packages/wandb/sdk/service/streams.py", line 206, in get_stream
    stream = self._streams[stream_id]
KeyError: 'zyeausrv'
```
given that this is  caused by `wandb` I was wondering if this was a wandb issue! 

(I tried as https://github.com/wandb/wandb/issues/3223#issuecomment-1032820724 says, by setting `os.environ["WANDB_START_METHOD"]="thread"` but the same problem occurred)

**Comment by sayakpaul** [comment]
Running into the same issue. 

I have tried the following but the issue persists. 

> (I tried as https://github.com/wandb/wandb/issues/3223#issuecomment-1032820724 says, by setting os.environ["WANDB_START_METHOD"]="thread" but the same problem occurred)

Here's the setup I am using. 

1. First, clone the Diffusers repo: `git clone https://github.com/huggingface/diffusers`.
2. Then head to examples folder: `cd examples/text_to_image`. 
3. Install the dependencies. 
4. Now, run:

   ```bash
	export MODEL_NAME="CompVis/stable-diffusion-v1-4"
	export DATASET_NAME="lambdalabs/pokemon-blip-captions"


	accelerate launch --mixed_precision="fp16" train_text_to_image_lora.py \
	  --pretrained_model_name_or_path=$MODEL_NAME \
	  --dataset_name=$DATASET_NAME --caption_column="text" \
	  --resolution=512 --random_flip \
	  --train_batch_size=1 \
	  --max_train_steps=5 \
	  --learning_rate=1e-04 --lr_scheduler="constant" --lr_warmup_steps=0 \
	  --seed=42 \
	  --validation_prompt="cute creature" \
	  --report_to="wandb" \
	  --output_dir="sd-pokemon-model-lora" && sudo shutdown now
  ```

A GPU like V100 should be sufficient to reproduce the bug.

**Comment by emilysilcock** [comment]
Also having the same error here!

**Comment by WOKNz** [comment]
I think the same issue here...

Exception in thread SockSrvRdThr:
Traceback (most recent call last):
  File "C:\Users\absde\miniconda3\envs\vit_v1_env\lib\threading.py", line 1016, in _bootstrap_inner
Sanity Checking: 0it [00:00, ?it/s]    self.run()
  File "C:\Users\absde\miniconda3\envs\vit_v1_env\lib\site-packages\wandb\sdk\service\server_sock.py", line 112, in run
    shandler(sreq)
  File "C:\Users\absde\miniconda3\envs\vit_v1_env\lib\site-packages\wandb\sdk\service\server_sock.py", line 174, in server_record_publish
    iface = self._mux.get_stream(stream_id).interface
  File "C:\Users\absde\miniconda3\envs\vit_v1_env\lib\site-packages\wandb\sdk\service\streams.py", line 206, in get_stream
    stream = self._streams[stream_id]
KeyError: 'd5mbguuf'

**Comment by ArtsiomWB** [comment]
Hi guys! Could you send debug logs and debug internal logs for the runs that are crashing?

**Comment by sayakpaul** [comment]
I got the same as what was posted in the first comment.

**Comment by emilysilcock** [comment]
@ArtsiomWB I am also getting the same as in the first comment - the other thing to add is that the runs are actually crashing, just stopping, so I don't get a debug log or crash report. 

It seems to happen quite randomly - I'm running a sweep and it's stopping, for example, on the 4th run of the sweep, 21% of the way through the run - and running fine until there. I've tried running it multiple times and it always stops, but it doesn't seem to be at any predictable run or point. 

I actually left it running and it's still going (after a week or so) but hasn't done anything. There's a bit of an addition to the terminal output, but I don't think it's super helpful, but pasting below in case it is. 

When looking for the logs, there is no directory at ./wandb/run-20230202_094826-f6n0h5to (although I have the logs for plenty of other runs at the same location), which tied up with the "key error" error message. It seems that somehow the run log is being deleted mid-process? I have the relevant config file created in the sweep directory though. 

Thanks!


```
 21%|██████████████████████████████▊                                                                                                                   | 3400/16089 [07:39<28:35,  7.40it/s]Exception in thread SockSrvRdThr:                                                                                                                                                           Traceback (most recent call last):                                                                                                                                                            File "/home/silcock/.conda/envs/ner/lib/python3.8/threading.py", line 932, in _bootstrap_inner                                                                                                self.run()                                                                                                                                                                                File "/home/silcock/.conda/envs/ner/lib/python3.8/site-packages/wandb/sdk/service/server_sock.py", line 112, in run                                                                           shandler(sreq)                                                                                                                                                                            File "/home/silcock/.conda/envs/ner/lib/python3.8/site-packages/wandb/sdk/service/server_sock.py", line 174, in server_record_publish                                                         iface = self._mux.get_stream(stream_id).interface                                                                                                                                         File "/home/silcock/.conda/envs/ner/lib/python3.8/site-packages/wandb/sdk/service/streams.py", line 206, in get_stream                                                                        stream = self._streams[stream_id]                                                                                                                                                       KeyError: 'f6n0h5to'                                                                                                                                                                        502 response executing GraphQL.                                                                                                                                                                                                                                                                                                                                                         <html><head>                                                                                                                                                                                <meta http-equiv="content-type" content="text/html;charset=utf-8">                                                                                                                          <title>502 Server Error</title>                                                                                                                                                             </head>                                                                                                                                                                                     <body text=#000000 bgcolor=#ffffff><h1>Error: Server Error</h1><h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2><h2></h2></body></html>

502 response executing GraphQL.

<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">                                                                                                                          <title>502 Server Error</title></head><body text=#000000 bgcolor=#ffffff><h1>Error: Server Error</h1><h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2><h2></h2></body></html>

500 response executing GraphQL.
{"errors":[{"message":"context deadline exceeded"}]}
wandb: ERROR Error while calling W&B API: context deadline exceeded (<Response [500]>)
500 response executing GraphQL.
{"error":"internal database error"}
500 response executing GraphQL.
{"errors":[{"message":"internal database error","path":["agentHeartbeat"]}],"data":{"agentHeartbeat":null}}
wandb: ERROR Error while calling W&B API: internal database error (<Response [500]>)
500 response executing GraphQL.
{"error":"internal database error"}
wandb: Network error (HTTPError), entering retry loop.
500 response executing GraphQL.
{"errors":[{"message":"internal database error","path":["agentHeartbeat"]}],"data":{"agentHeartbeat":null}}
wandb: ERROR Error while calling W&B API: internal database error (<Response [500]>)
500 response executing GraphQL.
{"error":"internal database error"}
500 response executing GraphQL.
{"error":"internal database error"}
500 response executing GraphQL.
```

It continues like this a bit and then I get some time out errors.

**Comment by ArtsiomWB** [comment]
Strange that you don't have the debug logs. Can @dyhan316 send them to me? 

@emilysilcock do you happen to have logs from any other runs that have crashed? Or does it always remove them for you?

**Comment by harrywang** [comment]
> Running into the same issue.
> 
> I have tried the following but the issue persists.
> 
> > (I tried as [#3223 (comment)](https://github.com/wandb/wandb/issues/3223#issuecomment-1032820724) says, by setting os.environ["WANDB_START_METHOD"]="thread" but the same problem occurred)
> 
> Here's the setup I am using.
> 
> 1. First, clone the Diffusers repo: `git clone https://github.com/huggingface/diffusers`.
> 2. Then head to examples folder: `cd examples/text_to_image`.
> 3. Install the dependencies.
> 4. Now, run:
>    ```shell
>     export MODEL_NAME="CompVis/stable-diffusion-v1-4"
>     export DATASET_NAME="lambdalabs/pokemon-blip-captions"
>    
>    
>     accelerate launch --mixed_precision="fp16" train_text_to_image_lora.py \
>       --pretrained_model_name_or_path=$MODEL_NAME \
>       --dataset_name=$DATASET_NAME --caption_column="text" \
>       --resolution=512 --random_flip \
>       --train_batch_size=1 \
>       --max_train_steps=5 \
>       --learning_rate=1e-04 --lr_scheduler="constant" --lr_warmup_steps=0 \
>       --seed=42 \
>       --validation_prompt="cute creature" \
>       --report_to="wandb" \
>       --output_dir="sd-pokemon-model-lora" && sudo shutdown now
>    ```
> 
> ```
> 
> A GPU like V100 should be sufficient to reproduce the bug. 
> ```

I got similar error running dreambooth on v100:

```
wandb: Waiting for W&B process to finish... (success).
wandb: 
wandb: Run history:
wandb: loss ▁▁▂▃▁▂▂█▁▃▂▃▂▂▁▁▁▂▂▁▁▃▂▁▂▁▁▁▂▂▁▁▁▁▁▂▂▁▁▁
wandb:   lr ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb: 
wandb: Run summary:
wandb: loss 0.02268
wandb:   lr 1e-05
wandb: 
wandb: 🚀 View run enchanting-darling-2 at: https://wandb.ai/harrywang/dreambooth/runs/apibzg5w
wandb: Synced 5 W&B file(s), 0 media file(s), 2 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20230214_214619-apibzg5w/logs
Steps: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 400/400 [04:05<00:00,  1.63it/s, loss=0.0227, lr=5e-6]
Exception in thread SockSrvRdThr:
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.10.9/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/data/User/wangjiannan/lora-sd-finetune/venv/lib/python3.10/site-packages/wandb/sdk/service/server_sock.py", line 112, in run
    shandler(sreq)
  File "/data/User/wangjiannan/lora-sd-finetune/venv/lib/python3.10/site-packages/wandb/sdk/service/server_sock.py", line 174, in server_record_publish
    iface = self._mux.get_stream(stream_id).interface
  File "/data/User/wangjiannan/lora-sd-finetune/venv/lib/python3.10/site-packages/wandb/sdk/service/streams.py", line 206, in get_stream
    stream = self._streams[stream_id]
KeyError: 'apibzg5w'
```

**Comment by harrywang** [comment]
log files.
[debug.log](https://github.com/wandb/wandb/files/10738816/debug.log)
[debug-internal.log](https://github.com/wandb/wandb/files/10738817/debug-internal.log)

**Comment by harrywang** [comment]
> Artsiom Skarakhod commented: Hi guys! Could you see if settins this env variable will solve this concern?
> 
> `WANDB_DISABLE_SERVICE=true`

This solved my problem - worked! Thanks!

**Comment by emilysilcock** [comment]
> Artsiom Skarakhod commented: Hi guys! Could you see if settins this env variable will solve this concern?
> 
> `WANDB_DISABLE_SERVICE=true`

This worked for me too! Thanks!

**Comment by f2010126** [comment]
Hi, I just tried this variable setting fix. WANDB_DISABLE_SERVICE=true did not help. 
Are there any other options or workarounds?

**Comment by ArtsiomWB** [comment]
Hi @f2010126! Send over your debug logs :)

**Comment by sayakpaul** [comment]
The logs are more or less similar in the threads that reported this error. I wonder what we might be missing out here.

**Comment by kptkin** [comment]
Hi @dyhan316 , @sayakpaul , @emilysilcock, @f2010126, @harrywang 

could you please share which version of wandb you are using? We had one issue that manifested in the above way that we solved in the latest release and i wanted to verify if this is the same issue. Also if you could provide a reproduction that would further help us debug this issue. 

I'm still looking into @harrywang repro and hopefully will be able to reproduce it on my end.

**Comment by sayakpaul** [comment]
Using the latest stable release and the reproduction of my issue is available here: https://github.com/wandb/wandb/issues/4872#issuecomment-1409920940.

Let me know if anything is unclear there.

**Comment by emilysilcock** [comment]
@kptkin I was running 0.13.09, but updating to 0.13.10 and running (without setting the environment parameter) does not fix this. Thanks!

**Comment by kptkin** [comment]
> Using the latest stable release and the reproduction of my issue is available here: [#4872 (comment)](https://github.com/wandb/wandb/issues/4872#issuecomment-1409920940).
> 
> Let me know if anything is unclear there.


Thanks a lot! This is enough information for now.

**Comment by kptkin** [comment]
> @kptkin I was running 0.13.09, but updating to 0.13.10 and running (without setting the environment parameter) does not fix this. Thanks!

Hi @emilysilcock. Thanks for the information. If you are willing to provide a reproduction it will be helpful to diagnose your case?

**Comment by bestpredicts** [comment]
same error here

**Comment by bestpredicts** [comment]
any update?

**Comment by kptkin** [comment]
Quick update, i was able to reproduce the issue based on the script provided by @harrywang. It seems to be related to our console logging, which we are working to fix for the upcoming release in the meantime, if you want to use `service` with your script you could turn off console logging by adding the following env variable: `WANDB_CONSOLE="off"`

**Comment by DomInvivo** [comment]
Hello everyone, I tried `export WANDB_DISABLE_SERVICE=true`, but the error changes to:
`wandb: ERROR Run 4flr874d errored: Exception('The wandb backend process has shutdown')`

Then I tried `export WANDB_CONSOLE="off"` but it doesn't change anything

**Comment by kptkin** [comment]
@DomInvivo It seems like your environment in a bad state. It is hard to say what's going on, without further information. Could you provide reproduction script and details about your setup?

**Comment by ArtsiomWB** [comment]
Hi @DomInvivo, I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by DomInvivo** [comment]
Hello @ArtsiomWB , thank you for the follow-up.

I updated to `wandb==0.14.0` and the error persists, although the printed statement is a bit different.

```python
Exception in thread SockSrvRdThr:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/nethome/dominiqueb/.venv/goli_ipu/lib/python3.8/site-packages/wandb/sdk/service/server_sock.py", line 112, in run
    shandler(sreq)
  File "/nethome/dominiqueb/.venv/goli_ipu/lib/python3.8/site-packages/wandb/sdk/service/server_sock.py", line 174, in server_record_publish
    iface = self._mux.get_stream(stream_id).interface
  File "/nethome/dominiqueb/.venv/goli_ipu/lib/python3.8/site-packages/wandb/sdk/service/streams.py", line 206, in get_stream
    stream = self._streams[stream_id]
KeyError: 'vcjfkwxs'
```

**Comment by kptkin** [comment]
@DomInvivo based on the partial traceback you provide it matches with the console issue. 
I think disabling console should work in your case, if not could you provide the debug logs and a repro if possible. 

- Is the run id of the completed run  is the same as the one printed in the traceback?
- Are you using tqdm in your code? we also saw that when console tracking is on and users have tqdm there is a case where same issue is observed.

**Comment by sayakpaul** [comment]
My problem is solved. Here's what I found out. 

My script was being killed in the background without letting `wandb` finishing the run. Once I ensure that my script was not existing the process unexpectedly, everything ran smoothly.

**Comment by DomInvivo** [comment]
@kptkin 

- Yes the run id in the traceback is the same as the completed run
- Yes I am using tqdm
- No, disabling the console doesn`t helped. I tried `WANDB_CONSOLE="off"` and `WANDB_DISABLE_SERVICE=true`, without success. If I understand correctly, I just need to copy-paste these in my terminal, right?

**Comment by kptkin** [comment]
> @kptkin
> 
> * Yes the run id in the traceback is the same as the completed run
> * Yes I am using tqdm
> * No, disabling the console doesn't helped. I tried `WANDB_CONSOLE="off"` and `WANDB_DISABLE_SERVICE=true`, without success. If I understand correctly, I just need to copy-paste these in my terminal, right?

yeah these environment variables that you need to setup before calling the training script. If you could provide the debug logs and a reproduction code, we could try and help you further.

**Comment by Naylenv** [comment]
I've set the following environment variables in my startup script:

```bash
export WANDB_DISABLE_SERVICE=true
export WANDB_CONSOLE="off"
```
My program consistently stops at step 44810. One epoch is 35847 steps, meaning all my data has been processed once. I'm using the diffusers library for multi-GPU training of a diffusion model and have no idea what's causing this issue.
<img width="1553" alt="Snipaste_2024-06-25_14-42-50" src="https://github.com/wandb/wandb/assets/45486779/a2a325b1-0a95-409b-95bb-e373cd919b30">

**Comment by Naylenv** [comment]
> I've set the following environment variables in my startup script:
> 
> ```shell
> export WANDB_DISABLE_SERVICE=true
> export WANDB_CONSOLE="off"
> ```
> 
> My program consistently stops at step 44810. One epoch is 35847 steps, meaning all my data has been processed once. I'm using the diffusers library for multi-GPU training of a diffusion model and have no idea what's causing this issue. when i use wandb 17.2 <img alt="Snipaste_2024-06-25_14-42-50" width="1553" src="https://private-user-images.githubusercontent.com/45486779/342611258-a2a325b1-0a95-409b-95bb-e373cd919b30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NzU3OTksIm5iZiI6MTcxOTQ3NTQ5OSwicGF0aCI6Ii80NTQ4Njc3OS8zNDI2MTEyNTgtYTJhMzI1YjEtMGE5NS00MDliLTk1YmItZTM3M2NkOTE5YjMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDA4MDQ1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4ZTM2N2JkZWRhYjk4NWNlZTZmM2E4OWIwNGIzZDQwNzg0NjA4ZDk0NDMzMTRjNDU2NmQxMWQ0YTczNTM3YWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kWQcGRWP-Wknj7pNcYvmpBOE653NASRAONiudjzUNXQ"> use wandb 13.X <img alt="image" width="1426" src="https://private-user-images.githubusercontent.com/45486779/342612175-4dd8ebce-729d-41c9-973c-fe5879697b39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NzU3OTksIm5iZiI6MTcxOTQ3NTQ5OSwicGF0aCI6Ii80NTQ4Njc3OS8zNDI2MTIxNzUtNGRkOGViY2UtNzI5ZC00MWM5LTk3M2MtZmU1ODc5Njk3YjM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDA4MDQ1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlOTIzZDQxZDcwZTljZjQ4YjY3YWQyNWFlZmNmYjk5ZDlkNWNmNjNlMDFmODVlYTI3M2M0Yjg0YTQ5ODE2Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n6EiaOS1sfAsICzQt1ra1EqtJZ8694TflTab9H3-ly4">
> 
> For context, the nodes are nearly identical, with one using a batch size of 12 and the other 32.

I'm very sorry, I made a mistake. There is no bug in wandb. The length of my tqdm bar was eight times longer than expected, and the program actually completed normally.

**Comment by Naylenv** [comment]
I'm very sorry, I made a mistake. There is no bug in wandb. The length of my tqdm bar was eight times longer than expected, and the program actually completed normally.
