### ISSUE TITLE
[CLI]: wandb.init() has timeout error

### ISSUE THREAD

**Issue by RobRomijnders** [wandb/wandb#5017]
### Describe the bug

wandb.init() within a pythonconsole works, but running an experiment, wandb.init() hangs. Why does wandb.init() experimence a network error? 

```shell
$ ./experiment.sh
wandb: Currently logged in as: robromijnders. Use `wandb login --relogin` to force relogin
wandb: Network error (ReadTimeout), entering retry loop.
Problem at: ...
wandb.errors.CommError: Error communicating with wandb process, exiting...
For more info see: https://docs.wandb.ai/library/init#init-start-error


$ python3
Python 3.9.14 (main, Sep  7 2022, 23:43:48) 
[GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import wandb
>>> wandb.init()
wandb: Currently logged in as: robromijnders. Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.13.10
wandb: Run data is saved locally in ...
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run laced-planet-523
wandb:  View project at https://wandb.ai/robromijnders/dpfn
wandb: 🚀 View run at https://wandb.ai/robromijnders/dpfn/runs/l593t7tn
<wandb.sdk.wandb_run.Run object at 0x7ff608129610>
>>> 
```

### Environment

WandB version: 0.13.10

OS: Ubuntu 22

Python version: 3.9.14

Versions of relevant libraries:

**Comment by ramit-wandb** [comment]
Hi @RobRomijnders,

Have you redacted a certain piece of the output from the original message or is this exactly how the error was printed?

```
wandb: Network error (ReadTimeout), entering retry loop.
Problem at: ...
```

Looks like there might be a stack trace missing here.

Thanks,
Ramit

**Comment by tychovdo** [comment]
I'm facing a similar issue. Could this be a server-side issue?

The status page https://status.wandb.com/ shows "All Systems Operational", thought.

For me it hangs for a while at
```
wandb: / Waiting for wandb.init()...
```
and then crashes with the following trace
```
wandb: Currently logged in as: XXX. Use `wandb login --relogin` to force relogin
wandb: Network error (ReadTimeout), entering retry loop.
Problem at: XXX.py 405 <module>
Traceback (most recent call last):
  File "/vol/bitbucket/tv21/anaconda3/envs/py39/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1108, in init
    run = wi.init()
  File "/vol/bitbucket/tv21/anaconda3/envs/py39/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 742, in init
    raise error
wandb.errors.CommError: Error communicating with wandb process, exiting...
For more info see: https://docs.wandb.ai/library/init#init-start-error
wandb: ERROR Abnormal program exit
Traceback (most recent call last):
  File "/vol/bitbucket/tv21/anaconda3/envs/py39/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1108, in init
    run = wi.init()
  File "/vol/bitbucket/tv21/anaconda3/envs/py39/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 742, in init
    raise error
wandb.errors.CommError: Error communicating with wandb process, exiting...
For more info see: https://docs.wandb.ai/library/init#init-start-error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "XXX.py", line XXX, in <module>
    wandb.init(project='XXX', config=config, name=run_name, tags=tags,
  File "/XXX/anaconda3/envs/py39/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1145, in init
    raise Exception("problem") from error_seen
Exception: problem
```
I redacted personal project directories and files with XXX.
The line 405 refers to the line where `wandb.init()` is called in the project, which used to work just fine.

**Comment by RobRomijnders** [comment]
More people in my lab had the same issue. Though an half hour after OP, the error was resolved. I assume this was a small hiccup in the WandB server-side?

@ramit-wandb the traceback had some sensitive info, so i left it out.

**Comment by tychovdo** [comment]
Yes, everything seems sorted. wandb.init also works for me again.

**Comment by ramit-wandb** [comment]
This most likely happened from the high traffic we were noticing yesterday. I'm glad everything has been resolved now though. I'll be closing this issue out in that case, please reach back out to us in case you run into any issue again.

Thanks!
Ramit

**Comment by Porthoos** [comment]
Hello, I've started using W&B recently, and I met a similar issue. the output of the program is `wandb: Network error (ReadTimeout), entering retry loop.`, is this a problem about my computer or the server?

I'm using W&B 0.14.0
python 3.8.13
OS windows 10

the full output of program is

> wandb: W&B API key is configured. Use wandb login --relogin to force relogin
wandb: Network error (ReadTimeout), entering retry loop.
wandb: Network error (ReadTimeout), entering retry loop.
Traceback (most recent call last):
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\wandb\sdk\wandb_init.py", line 1144, in init
    run = wi.init()
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\wandb\sdk\wandb_init.py", line 773, in init
    raise error
wandb.errors.CommError: Error communicating with wandb process, exiting...
For more info see: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Problem at: D:\PycharmProjects\PPOimplementation\PPOmain.py 108 main
wandb: ERROR Abnormal program exit


the file debug-internal.log is

> 2023-04-03 10:28:53,689 INFO    StreamThr :7284 [internal.py:wandb_internal():87] W&B internal server running at pid: 7284, started at: 2023-04-03 10:28:53.688300
2023-04-03 10:28:53,692 DEBUG   HandlerThread:7284 [handler.py:handle_request():144] handle_request: status
2023-04-03 10:28:53,748 INFO    WriterThread:7284 [datastore.py:open_for_write():85] open: D:\PycharmProjects\PPOimplementation\wandb\run-20230403_102853-emaoap72\run-emaoap72.wandb
2023-04-03 10:28:53,754 DEBUG   SenderThread:7284 [sender.py:send():336] send: header
2023-04-03 10:28:53,921 DEBUG   SenderThread:7284 [sender.py:send():336] send: run
2023-04-03 10:28:58,964 DEBUG   HandlerThread:7284 [handler.py:handle_request():144] handle_request: keepalive
2023-04-03 10:29:04,013 DEBUG   HandlerThread:7284 [handler.py:handle_request():144] handle_request: keepalive
2023-04-03 10:29:09,064 DEBUG   HandlerThread:7284 [handler.py:handle_request():144] handle_request: keepalive
2023-04-03 10:29:14,126 DEBUG   HandlerThread:7284 [handler.py:handle_request():144] handle_request: keepalive
2023-04-03 10:29:19,187 DEBUG   HandlerThread:7284 [handler.py:handle_request():144] handle_request: keepalive
2023-04-03 10:29:24,234 DEBUG   HandlerThread:7284 [handler.py:handle_request():144] handle_request: keepalive
2023-04-03 10:29:29,301 DEBUG   HandlerThread:7284 [handler.py:handle_request():144] handle_request: keepalive
2023-04-03 10:29:34,084 INFO    SenderThread:7284 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\urllib3\connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\urllib3\connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\http\client.py", line 1348, in getresponse
    response.begin()
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\http\client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\http\client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\urllib3\util\retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\urllib3\packages\six.py", line 770, in reraise
    raise value
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\urllib3\connectionpool.py", line 451, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\urllib3\connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=10)

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\wandb\sdk\internal\internal_api.py", line 243, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\transport\requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\requests\adapters.py", line 578, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=10)
2023-04-03 10:29:34,365 DEBUG   HandlerThread:7284 [handler.py:handle_request():144] handle_request: keepalive
2023-04-03 10:29:39,584 DEBUG   HandlerThread:7284 [handler.py:handle_request():144] handle_request: keepalive
2023-04-03 10:29:44,606 DEBUG   HandlerThread:7284 [handler.py:handle_request():144] handle_request: keepalive
2023-04-03 10:29:49,634 DEBUG   HandlerThread:7284 [handler.py:handle_request():144] handle_request: keepalive
2023-04-03 10:29:54,674 DEBUG   HandlerThread:7284 [handler.py:handle_request():144] handle_request: cancel
2023-04-03 10:29:54,675 DEBUG   SenderThread:7284 [sender.py:send():345] Record cancelled: run
2023-04-03 10:29:54,675 DEBUG   HandlerThread:7284 [handler.py:handle_request():144] handle_request: cancel
2023-04-03 10:29:54,676 DEBUG   HandlerThread:7284 [handler.py:handle_request():144] handle_request: status_report
2023-04-03 10:29:59,514 INFO    MainThread:7284 [internal.py:handle_exit():77] Internal process exited

**Comment by lhallee** [comment]
Hi @ramit-wandb,
I am getting the following error repeatedly in a colab runtime with fresh install wandb. Upgrading to eventlet did not fix.

Waiting for wandb.init()...
Problem at: <ipython-input-19-d15e7a76e733> 1 <cell line: 1>
---------------------------------------------------------------------------
CommError                                 Traceback (most recent call last)
[<ipython-input-19-d15e7a76e733>](https://localhost:8080/#) in <cell line: 1>()
----> 1 wandb.init()

2 frames
[/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_init.py](https://localhost:8080/#) in init(job_type, dir, config, project, entity, reinit, tags, group, name, notes, magic, config_exclude_keys, config_include_keys, anonymous, mode, allow_val_change, resume, force, tensorboard, sync_tensorboard, monitor_gym, save_code, id, settings)
   1187         if logger is not None:
   1188             logger.exception(str(e))
-> 1189         raise e
   1190     except KeyboardInterrupt as e:
   1191         assert logger

[/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_init.py](https://localhost:8080/#) in init(job_type, dir, config, project, entity, reinit, tags, group, name, notes, magic, config_exclude_keys, config_include_keys, anonymous, mode, allow_val_change, resume, force, tensorboard, sync_tensorboard, monitor_gym, save_code, id, settings)
   1168         except_exit = wi.settings._except_exit
   1169         try:
-> 1170             run = wi.init()
   1171             except_exit = wi.settings._except_exit
   1172         except (KeyboardInterrupt, Exception) as e:

[/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_init.py](https://localhost:8080/#) in init(self)
    783                 backend.cleanup()
    784                 self.teardown()
--> 785             raise error
    786 
    787         assert run_result is not None  # for mypy

CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-

**Comment by wangdach** [comment]
see https://github.com/wandb/wandb/issues/7671#issuecomment-2309639324

**Comment by Inwobodo** [comment]
I am getting this error

---------------------------------------------------------------------------
CommError                                 Traceback (most recent call last)
[<ipython-input-24-84975b471bda>](https://localhost:8080/#) in <cell line: 1>()
----> 1 run = wandb.init(project="house price prediction", entity="nwobodope")
      2 print(run.id)

3 frames
[/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_init.py](https://localhost:8080/#) in init(self)
    830                 backend.cleanup()
    831                 self.teardown()
--> 832             raise error
    833 
    834         assert run_result is not None  # for mypy

CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
