### ISSUE TITLE
[App]: lots of errors in the app

### ISSUE THREAD

**Issue by davidgilbertson** [wandb/wandb#5367]
### Current Behavior

Over the past few hours I've gotten several errors. Sometimes individual panels not rendering (after having rendered for a long time, so the config is fine) sometimes the Sentry "Crash report" window, I get that a few times a day.

![image](https://user-images.githubusercontent.com/4443482/232976949-eed3ae90-49bc-4f1b-bc95-15793b42d2fd.png)

In the dev tools console, a quartet of GraphQL errors occurred with the latest "It looks like we're having issues." crash report .
```
GraphQL error: An internal error occurred. Please contact support.
GraphQL error: An internal error occurred. Please contact support.
GraphQL error: Error 1040 (08004): Too many connections
GraphQL error: An internal error occurred. Please contact support.
 ```

Sometimes if flicks up a 404 message (replacing the whole page) when I haven't even touched anything.

And today a new one about it not being able to display my custom panel (after having rendered for a long time, and refreshing fixed it, so the error is incorrect in only giving me one option: to lose my custom charts). 

```
There was a problem rendering these panels.
Click this button to reset your workspace to the default layout.
This preserves runs, but custom charts will be lost.
```
![image](https://user-images.githubusercontent.com/4443482/232974301-1885ae06-a249-44c8-8921-cad479c0fa28.png)

And in the CLI network errors a few times a day (I have a rock solid network, usually coincides with some error in the web app so I assume WandB servers failing somewhere).

E.g. An internal error occurred. Please contact support

![image](https://user-images.githubusercontent.com/4443482/232972036-cfb46b5d-852f-4a57-9bad-f6f4a3409b9f.png)

### Environment

OS: Windows 11

Browsers: Chrome

Version: 0.14

**Comment by CeHao1** [comment]
+1, I also faced this error many times.

**Comment by CeHao1** [comment]
Now it is fixed. No problem any more. Thanks.

**Comment by ZedRover** [comment]
Now there still exists this problem for me. It happened 2 times  today, and each  one lasts about 10 minutes.

**Comment by davidgilbertson** [comment]
It's no longer happening for me, but I'll leave the issue open since @ZedRover appears to be having issues still.

**Comment by rsanandres-wandb** [comment]
@ZedRover 

Could you provide me with the following so I can debug your issue:
- a link to your workspace
- the browser console logs for when the `An internal error occurs` pops up

**Comment by SimiPixel** [comment]
I get this bug extremely frequently since a couple of days. About once every 1-2 minutes. It's very annoying. Any ideas?

**Comment by leonmkim** [comment]
Just to chip in, I have also encountered this issue recently in the past few days and it's still persisting beyond the big outage last week.

**Comment by sydholl** [comment]
We are closing this issue due to inactivity. If you feel that it merits additional review, please provide a reproduction and add a comment explaining why. Thank you.
