### ISSUE TITLE
[Q] ModuleNotFoundError: No module named 'wandb.keras'

### ISSUE THREAD

**Issue by marlens123** [wandb/wandb#6195]
hey! I am using wandb==0.15.3 and keep getting a ModuleNotFoundError when trying to execute 

```from wandb.keras import WandbMetrcsLogger```.

When trying to execute

```wandb.login()```

I am getting an AttributeError: 

```module 'wandb' has no attribute 'login'```

Both code chunks used to work a month ago within the same conda environment. Am I missing something?

I appreciate any help!

**Comment by thanos-wandb** [comment]
Hi @marlens123 thanks for reporting this issue. Could you please try to do the following two things then try to run the script again:

- Check to see if there is a wandb.py within the same directory that may be conflicting with wandb and move the file into a different directory

- Uninstall and reinstall wandb in same virtual environment

Would any of these work for you?

**Comment by marlens123** [comment]
Hi @thanos-wandb thanks for the reply! I have another wandb project set up, though on a different drive. Reinstallation does not help, unfortunately.

**Comment by thanos-wandb** [comment]
Hi @marlens123 sorry this didn't work for you. Could you please provide some more information where you're running your script, is it in your local machine, external cluster or a notebook? Would it be please possible to share a screenshot from your terminal? and also try to list all files in your current working directory and check for any scripts that you might have named them as wandb.py?

**Comment by sydholl** [comment]
WandB Internal User commented: 
thanos-wandb commented: 
Hi @marlens123 thanks for reporting this issue. Could you please try to do the following two things then try to run the script again:

- Check to see if there is a wandb.py within the same directory that may be conflicting with wandb and move the file into a different directory

- Uninstall and reinstall wandb in same virtual environment

Would any of these work for you?

**Comment by sydholl** [comment]
WandB Internal User commented: 
thanos-wandb commented: 
Hi @marlens123 sorry this didn't work for you. Could you please provide some more information where you're running your script, is it in your local machine, external cluster or a notebook? Would it be please possible to share a screenshot from your terminal? and also try to list all files in your current working directory and check for any scripts that you might have named them as wandb.py?

**Comment by thanos-wandb** [comment]
Hi @marlens123 just checking in here to see if that issue still persists for you, or if it's been resolved? Could you please provide us with some additional information requested in previous message? Thank you!

**Comment by marlens123** [comment]
Hi @thanos-wandb sorry for the delayed message! I am running on my local machine and attached my terminal and directory content. Thank you!

![terminal](https://github.com/wandb/wandb/assets/80780236/079e792e-30a7-4f33-a139-48684b7ccb54)
![dir](https://github.com/wandb/wandb/assets/80780236/7bae623a-536d-4ced-a573-08f6799a1fac)

**Comment by thanos-wandb** [comment]
Hi @marlens123 thanks so much for reporting this issue. Could you please try to `pip install --upgrade wandb` as this issue seems to have been resolved in our newer versions?

**Comment by marlens123** [comment]
Hi @thanos-wandb thank you for coming back to me! I just pip upgraded wandb and reactivated the environment, but unfortunately the error still persists:
![Unbenannt](https://github.com/wandb/wandb/assets/80780236/2d72d19a-295c-4569-8364-719f9a1ed8d4)

**Comment by thanos-wandb** [comment]
Hi @marlens123 thanks for trying this. Could you please provide us with your keras and tensorflow versions too?

**Comment by marlens123** [comment]
hi @thanos-wandb, I am using keras==2.10.0 and tensorflow-gpu==2.10.0

**Comment by thanos-wandb** [comment]
Hi @marlens123 I wasn't able to recreate the issue using same wandb, keras, and tensorflow versions. Could you please try to create a new virtual environment and check again? Would the following code work for you?


```
import random
import numpy as np
import tensorflow as tf
from wandb.keras import WandbMetricsLogger, WandbModelCheckpoint

# Simple Keras Model

# Launch 5 experiments, trying different dropout rates
for run in range(5):
    # Start a run, tracking hyperparameters
    wandb.init(
        project="keras-intro",
        # (optional) set entity to specify your username or team name
        # entity="my_team",
        config={
            "layer_1": 512,
            "activation_1": "relu",
            "dropout": random.uniform(0.01, 0.80),
            "layer_2": 10,
            "activation_2": "softmax",
            "optimizer": "sgd",
            "loss": "sparse_categorical_crossentropy",
            "metric": "accuracy",
            "epoch": 6,
            "batch_size": 256,
        },
    )
    config = wandb.config

    # Get the data
    mnist = tf.keras.datasets.mnist
    (x_train, y_train), (x_test, y_test) = mnist.load_data()
    x_train, x_test = x_train / 255.0, x_test / 255.0
    x_train, y_train = x_train[::5], y_train[::5]  # Subset data for a faster demo
    x_test, y_test = x_test[::20], y_test[::20]
    labels = [str(digit) for digit in range(np.max(y_train) + 1)]

    # Build a model
    model = tf.keras.models.Sequential(
        [
            tf.keras.layers.Flatten(input_shape=(28, 28)),
            tf.keras.layers.Dense(config.layer_1, activation=config.activation_1),
            tf.keras.layers.Dropout(config.dropout),
            tf.keras.layers.Dense(config.layer_2, activation=config.activation_2),
        ]
    )

    model.compile(optimizer=config.optimizer, loss=config.loss, metrics=[config.metric])

    # Add WandbMetricsLogger to log metrics and WandbModelCheckpoint to log model checkpoints
    wandb_callbacks = [
        WandbMetricsLogger(),
        WandbModelCheckpoint(filepath="my_model_{epoch:02d}"),
    ]

    model.fit(
        x=x_train,
        y=y_train,
        epochs=config.epoch,
        batch_size=config.batch_size,
        validation_data=(x_test, y_test),
        callbacks=wandb_callbacks,
    )

    # Mark the run as finished
    wandb.finish()
```

**Comment by thanos-wandb** [comment]
Hi @marlens123 I wanted to follow up with you regarding your support request as we have not heard back from you. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by thanos-wandb** [comment]
Hi @marlens123 since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know and we will be happy to keep investigating!

**Comment by Ibaii99** [comment]
This has happened to me with wandb-0.17.0

Solved by importing as:  
```
from wandb.integration.keras import WandbMetricsLogger
```

**Comment by Ravikumarchavva** [comment]
@iguillenp Thanks it worked for me in 0.17 version
