### ISSUE TITLE
[CLI]: `early_terminate` param for sweep configuration does not work at all

### ISSUE THREAD

**Issue by yiphei** [wandb/wandb#7156]
### Describe the bug

(technically, since the sweep feature is serviced by your own backend, this is not a bug on the wandb client) 

The `early_terminate` param for the sweep configuration does not work at all in my testing. I actually read the source code implementation (https://github.com/wandb/sweeps/blob/6e25b8bcf2adada723538e675c6de34f5faebb22/src/sweeps/hyperband_stopping.py#L48) since the documentation is [atrocious](https://github.com/wandb/wandb/issues/4481), so I tried to test `early_terminate` for myself. Here is a report of the test using a dummy sweep: https://api.wandb.ai/links/yanyiphei/9um766xr (I wanted to share the sweep directly but I dont think theres a way (???) so I just pasted the sweep yaml config and all available charts).

Now, referencing both the report and the source code, you can see that the first bracket is `4`. therefore, the `threshold` (see source code for what this is) should be `4.049`. Now, because the history of `visionary-sweep-2` has a min loss value of `4.504` within the first bracket, it should be early terminated at the first bracket per the implementation. However, it is not. In fact, it should be early terminated for every successive bracket but it continues to run until completion.

So either there is a bug or something not present in the code or documentation is causing bizarre behaviors (e.g. maybe the early terminate check is run async or on some (very slow) polling rate)

```python

```

```shell

```

### Environment

WandB version: 0.16.3

OS: 14.3.1 (23D60)

Python version: 3.10.1

Versions of relevant libraries:

**Comment by yiphei** [comment]
I just did some debugging directly in the source code and found that all my sweep runs have empty history (i.e. `run.history = []`, not just for the target goal metric but for all metrics logged. So this explains why early termination is not working at all. Why is no history saved for my sweep runs? I setup my sweep configuration by simply following your tutorials.

**Comment by yiphei** [comment]
after some more digging, I think I found the bug. The early termination function expects the metric history to be stored in the `.history` attribute of the run, but when the controller queries for the runs (which are eventually passed to the early termination function), it runs the following GQL query
```
            """
        query SweepWithRuns($entity: String, $project: String, $sweep: String!, $specs: [JSONString!]!) {
            project(name: $project, entityName: $entity) {
                sweep(sweepName: $sweep) {
                    id
                    name
                    method
                    state
                    description
                    config
                    createdAt
                    heartbeatAt
                    updatedAt
                    earlyStopJobRunning
                    bestLoss
                    controller
                    scheduler
                    runs {
                        edges {
                            node {
                                name
                                state
                                config
                                exitcode
                                heartbeatAt
                                shouldStop
                                failed
                                stopped
                                running
                                summaryMetrics
                                sampledHistory(specs: $specs)
                            }
                        }
                    }
                }
            }
        }
        """
```
so it doesnt even query for the `history`, only for `sampledHistory`.

**Comment by yiphei** [comment]
oh but I see that you are doing this https://github.com/wandb/sweeps/blob/6e25b8bcf2adada723538e675c6de34f5faebb22/src/sweeps/run.py#L74, thus loading history from sampled history

**Comment by yiphei** [comment]
ok I think I found the bug now. When you call `_sweep_object_read_from_backend`, you set `self._sweep_metric` after you run the query (https://github.com/wandb/wandb/blob/1ae34d584eec9fbf3b21bd02108ce278a70f665a/wandb/wandb_controller.py#L443), but the code expects `self._sweep_metric` to be set in order to create the specs for the sample history (https://github.com/wandb/wandb/blob/1ae34d584eec9fbf3b21bd02108ce278a70f665a/wandb/wandb_controller.py#L432)

**Comment by yiphei** [comment]
oh, and another issue. The current pip version of `sweeps` has the following incorrect implementation: `h[band]` treats the band values as 1-indexed (https://github.com/wandb/sweeps/blob/95d3ccad7ef6ce7c7af77b5bf7efd933b50b9336/src/sweeps/hyperband_stopping.py#L189), but the latest commit on main has the correct implementation: `h[band-1]` treating the brand values as 0-indexed (https://github.com/wandb/sweeps/blob/master/src/sweeps/hyperband_stopping.py#L189). this also explains why my specific example above didnt trigger early termination

**Comment by yiphei** [comment]
I applied all these changes locally and everything works, including the specific example in the description. pls fix this asap because my ML workflow is heavily reliant on early termination working.

**Comment by sydholl** [comment]
WandB Internal User commented: 
yiphei commented: 
after some more digging, I think I found the bug. The early termination function expects the metric history to be stored in the `.history` attribute of the run, but when the controller queries for the runs (which are eventually passed to the early termination function), it runs the following GQL query
```
            """
        query SweepWithRuns($entity: String, $project: String, $sweep: String!, $specs: [JSONString!]!) {
            project(name: $project, entityName: $entity) {
                sweep(sweepName: $sweep) {
                    id
                    name
                    method
                    state
                    description
                    config
                    createdAt
                    heartbeatAt
                    updatedAt
                    earlyStopJobRunning
                    bestLoss
                    controller
                    scheduler
                    runs {
                        edges {
                            node {
                                name
                                state
                                config
                                exitcode
                                heartbeatAt
                                shouldStop
                                failed
                                stopped
                                running
                                summaryMetrics
                                sampledHistory(specs: $specs)
                            }
                        }
                    }
                }
            }
        }
        """
```
so it doesnt even query for the `history`, only for `sampledHistory`.

**Comment by sydholl** [comment]
WandB Internal User commented: 
yiphei commented: 
oh, and another issue. The current pip version of `sweeps` has the following incorrect implementation: `h[band]` treats the band values as 1-indexed (https://github.com/wandb/sweeps/blob/95d3ccad7ef6ce7c7af77b5bf7efd933b50b9336/src/sweeps/hyperband_stopping.py#L189), but the latest commit on main has the correct implementation: `h[band-1]` treating the brand values as 0-indexed (https://github.com/wandb/sweeps/blob/master/src/sweeps/hyperband_stopping.py#L189). this also explains why my specific example above didnt trigger early termination

**Comment by sydholl** [comment]
WandB Internal User commented: 
yiphei commented: 
I applied all these changes locally and everything works, including the specific example in the description. pls fix this asap because my ML workflow is heavily reliant on early termination working.

**Comment by Eunchan24** [comment]
The early_terminate parameter for the sweep configuration does not work at all in my test.
Is there any progress on this issue?

**Comment by yiphei** [comment]
they released a fix so it should work now.

**Comment by thanos-wandb** [comment]
Hi @Eunchan24 @yiphei this should be resolved now. Can you please add some `time.sleep()` calls between your experiments as it might be related that your runs are executed faster than the Sweep server checks?

**Comment by wandb-kc** [comment]
WandB Internal User commented: 
yiphei commented: 
actually, it still doesnt fully work. I followed up in https://community.wandb.ai/t/early-terminate-param-for-sweep-configuration-does-not-seem-to-work-at-all/6094/20.
