### ISSUE TITLE
[Q]: My result was drawn with two Outlines, and the data values were inconsistent with the log file records

### ISSUE THREAD

**Issue by zearo-github** [wandb/wandb#8301]
### Ask your question

![image](https://github.com/user-attachments/assets/f8487bd2-73be-4447-94ce-1b0a4525edb9)

As shown in the figure, the red line is the result of my previous experiments, and there is no problem with the drawing. The yellow broken line is problematic, its value is wrong, and there are two surrounding lines of unknown meaning. 

The problem was discovered last Saturday and I ran my program again and still had the same problem. But the wandb part of my code hasn't changed, and it's the same code I used to draw the red line.

The result rendering error interfered with my analysis of the experimental results. I was confused and upset and wanted someone to help me！

**Comment by waymao** [comment]
I have the same issue. It was working fine before last Saturday, but it stopped working this last Sunday (9/8).

**Comment by C-J-Cundy** [comment]
I'm having the same issue

**Comment by JoanaMarieL** [comment]
Hi @zearo-github , thank you for writing in, is it possible to share your run link for us to review? same with you guys @waymao @C-J-Cundy ~

**Comment by zearo-github** [comment]
emmm... What do I need to provide? Here is my runs' overview page link: https://wandb.ai/cost-z/FasterMETRO/runs/tmyetth4/overview

**Comment by zearo-github** [comment]
@JoanaMarieL

**Comment by sephmard** [comment]
Hi @zearo-github, this was a bug and has been fixed. More generally, we have been making improvements to our existing line plot charts. The previous random sampling method in W&B line plots limited data visibility by capping at 1,500 points, potentially leading to missed outliers and spikes in larger training runs. The new solution uses point aggregation across buckets to preserve minimum and maximum values, and include signal from all data points, offering a more accurate and detailed representation of training data without compromising data integrity during zooming or overall analysis.

Key Features:

- Enhanced Visibility: See all outliers and spikes in long or large jobs, ensuring no data is missed.
- Improved Line Detail: Displays minimum, maximum, and average values for a complete overview.
- Zoom Without Data Loss: Spot outliers and dive deeper into your data seamlessly.

The shaded areas represent the min/max values of the buckets. You can revert back to the legacy sampling approach using workspace settings (Settings > Runs > Random Sampling) or Panel Settings.

**Comment by leonmkim** [comment]
@sephmard 

As of writing, I'm still encountering this issue on the workspace of my runs. The line plots show shading despite there being no need for aggregation across multiple runs (I'm viewing the workspace of a single run). Furthermore, the solid line of the plots are technically correct, but skips over certain datapoints and even adds a non-existent one. 

However, when I expand the line plot to fullscreen, suddenly the plot corrects itself and is consistent with the underlying logged data. I've tried switching the point aggregation method from full fidelity to random sampling which gets rid of the shading but hides different datapoints.

Here's the [link](https://wandb.ai/serialexperimentsleon/extrinsic_contact_downstream/runs/39761_0) for the run in question. Please let me know if I need to change the visibility settings for the project.

Incorrect line plot:
![Image](https://github.com/user-attachments/assets/e3e15d23-e236-4d17-9698-dec720bb7bd7)

Correct line plot once expanded to full-screen:
![Image](https://github.com/user-attachments/assets/d19c7206-1b74-46bd-ad3d-ea2a6056c771)

CSV of the underlying data: 
[wandb_export_2025-03-18T11_12_59.060-04_00.csv](https://github.com/user-attachments/files/19322481/wandb_export_2025-03-18T11_12_59.060-04_00.csv)
