### ISSUE TITLE
[Feature]: Adding mmCIF file support for `wandb.Molecule`

### ISSUE THREAD

**Issue by amorehead** [wandb/wandb#9535]
### Description

The following error message displayed in the WandB UI after logging a table containing a `wandb.Molecule` object constructed from a `.cif` (i.e., mmCIF) file suggests that mmCIF files aren't supported, even though documentation suggests otherwise.

Log: `Tried to render media/molecule/1a335c7f618260e68830/sample.cif, but only .pdb files are currently supported.`

### Suggested Solution

It'd be great for mmCIF file support to be added for `wandb.Molecule` objects, as the PDB file format has long since been deprecated in favor of mmCIF files (according to the RCSB PDB).

**Comment by ArtsiomWB** [comment]
Hey @amorehead, thank you for writing in. 

Could you please send me an example script of how you are logging your molecule to wandb? I am trying to get the exact same error.

**Comment by amorehead** [comment]
Hi, @ArtsiomWB. Attached is one such mmCIF file (renamed to .txt to upload to GitHub) that failed to display properly in the WandB UI. Let me know if you have any follow-up questions.

[sample.cif.txt](https://github.com/user-attachments/files/19099265/sample.cif.txt)

**Comment by ArtsiomWB** [comment]
Thank you for sending it over. Even though I am logging a .cif file I am still seeing this error:
```ValueError: Molecule only supports files of the type: sdf, mmtf, pqr, pdb, sd, mcif, cif, mol2, gro, mmcif```
I'll go ahead and report it to our eng team. I'll let you know as soon as I get any updates from them.

**Comment by amorehead** [comment]
Thanks for your help, @ArtsiomWB. Let me know if you need any other information to help debug this issue. My hunch is there's some kind of necessary metadata missing in these mmCIF files I'm creating that WandB requires for visualization.

**Comment by amorehead** [comment]
Hi, @ArtsiomWB. I hope all is well on your end. I was curious if you have heard back from the WandB engineering team about this issue. It would be helpful to have CIF files plotting correctly in the WandB UI.

**Comment by ArtsiomWB** [comment]
Could you try logging your molecule to wandb now? I think the error should now be fixed on the client's side and now we need to look into it from the App's side instead

**Comment by amorehead** [comment]
Hi, @ArtsiomWB. Yes, for table rows logged within the last few hours, I'm still not able to see their associated CIF files rendered in the WandB UI: 

![Image](https://github.com/user-attachments/assets/1749a56f-003f-4180-9846-6011a315774e)

**Comment by ArtsiomWB** [comment]
Thank you for the follow-up!

I have sent a feature request to our Tables team to add the ability to log molecules in tables. It should be now enabled from the SDK's side but our frontend still doesn't know how to handle it.

**Comment by ArtsiomWB** [comment]
Quick update here, you should now be able to log cif-formatted molecules to tables in wandb.

**Comment by amorehead** [comment]
Thanks! I just checked, and it looks like I'm no longer seeing the original error message in my WandB tables. However, it seems like my CIF molecules are loading indefinitely in the UI. Could this be caused by issues in rendering (e.g., large or irregular) molecules in WandB's table UI?

**Comment by ArtsiomWB** [comment]
It could be because of the size... Could you please send me a molecule file you have logged to wandb that is loading indefinitely for you?

**Comment by ArtsiomWB** [comment]
Thank you for sending it over. 

That is very strange. I see a bank screen now when trying to display it in the UI. Will keep you posted.

**Comment by ArtsiomWB** [comment]
Hi there, I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by ArtsiomWB** [comment]
Hi, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!

**Comment by amorehead** [comment]
Hi, @ArtsiomWB. Thanks for looking into this for me, and apologies for my delayed response. I have not yet been able to test logging your CIF file within one of my tables (integrating it within my existing workflow is not simple). However, I am curious, are you able to log the CIF file I attached above? If not, that suggests there is some metadata in my CIF file that is either missing or unncessary (and confusing the WandB UI).

**Comment by ArtsiomWB** [comment]
When trying to log your CIF file It does get logged, and there is not error in the UI anymore. 

UI for some reason instead of displaying it, will keep on constantly loading:

<img width="866" alt="Image" src="https://github.com/user-attachments/assets/7027c542-f4a7-4cb2-ae7e-442d2785dd72" />

And I do see a couple of errors inside of the browser's console logs:

<img width="695" alt="Image" src="https://github.com/user-attachments/assets/61f1565e-5875-4e75-bc45-644f415eccad" />

**Comment by amorehead** [comment]
Thanks for looking into this for me. It seems there is indeed some missing metadata in this mmCIF file of mine. Is it somehow possible to find out which metadata are missing on the backend?

**Comment by amorehead** [comment]
Hi, @ArtsiomWB. Thanks for sharing this link with me. I cannot get my CIF file to load correctly with this service. However, I can load my CIF file using the RCSB PDB's official recommendation for molecule visualization software packages (i.e., MolStar: https://molstar.org/viewer/). This tells me WandB is relying on some piece of metadata that MolStar doesn't require for visualization. Once I find out what that is, I can modify how I am writing my CIF files to include this (necessary) metadata.

**Comment by ArtsiomWB** [comment]
Sounds like a plan, and I'll report the fact that your molecule is not loading and failing silently to our Tables Team. Thank you for bringing it up.
